[server]
enableCORS = false
enableXsrfProtection = false
port = 8501
address = "0.0.0.0"
maxUploadSize = 100

[theme]
base = "dark"
primaryColor = "#4caf50"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#161b22"
textColor = "#ffffff"
font = "sans serif"
